'use strict';
/**
 * Stamp + drift logic, shared by `audit/audit.mjs` (report) and `colab update` (report + refresh).
 *
 * Copy-and-own means nothing is pushed to an adopter: a copied artifact carries a STAMP naming
 * the template and the handbook version it came from, and drift is discovered by comparing that
 * stamp against the handbook's own git history. Both tools must read stamps identically — a
 * second implementation that disagreed about what "behind" means is exactly the two-places-drift
 * disease this handbook exists to kill, so the reading lives here once.
 *
 * CommonJS on purpose: `tools/colab` is CJS, `audit/audit.mjs` is ESM. CJS is the format both can
 * consume (the audit pulls it in through `createRequire`); the reverse is not true from a
 * synchronous CLI.
 *
 * Every function takes the handbook root explicitly rather than resolving it — the two callers
 * locate the handbook differently (the audit honours COLAB_HANDBOOK; the CLI walks up from its
 * own file), and a module that guessed would be wrong for one of them.
 */

const { execFileSync } = require('child_process');

// The artifact kinds that carry a stamp. Workflow copies are WHOLE-FILE copies, so a pristine one
// can be regenerated byte-for-byte. The CLAUDE block is a fragment pasted into a larger file whose
// placeholders the adopter fills in — see CLAUDE_BLOCK below.
const CLAUDE_BLOCK_TEMPLATE = 'templates/repo-CLAUDE-block.md';

// The FROZEN CLI copy: `install.sh --tools` copies `tools/colab` + `tools/lib/` into
// `<COLAB_HOME>/bin/` and writes the stamp beside it, so a long-lived process never resolves the
// CLI through a working tree. The symlink install (`~/.local/bin/colab`) is deliberately the
// opposite — a human session should follow whatever branch the handbook clone has checked out —
// but an always-on service must not change behaviour because somebody checked out an unrelated
// branch. Refreshing the frozen copy is therefore an act (re-run install.sh), never a side effect.
//
// The stamp is a SIDECAR file rather than a line prepended into the script: `colab` is executable
// with a shebang on line 1, and the sidecar keeps the copied bytes identical to the source.
// It uses the ordinary workflow stamp convention (`# colab-handbook: <name> @ <version>`) and is
// read with parseWorkflowStamp, so there is one stamp format on the machine, not two.
const FROZEN_STAMP_NAME = 'colab-bin';
const FROZEN_STAMP_FILE = 'STAMP';
// What the frozen copy is made of, as repo-relative paths — the same role `templateFiles()` plays
// for a template, and fed to the same `git log <stamp>..HEAD -- <paths>` question.
const FROZEN_SOURCES = ['tools/colab', 'tools/lib'];

// ---------------------------------------------------------------------------
// git access to the handbook checkout
// ---------------------------------------------------------------------------

function gitIn(root, args) {
  try {
    return {
      ok: true,
      out: execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(),
    };
  } catch (_) {
    return { ok: false, out: '' };
  }
}

/**
 * The handbook's own identity: { root, hasGit, untagged, version }.
 * Before the first tag exists the version is 'v0' and `untagged` is true, which DEACTIVATES stamp
 * comparison in both callers — there is no real version line to compare against, and inventing one
 * would mark every adopter stale against a version that never shipped.
 */
function handbookInfo(root) {
  if (!gitIn(root, ['rev-parse', '--show-toplevel']).ok) {
    return { root, hasGit: false, untagged: true, version: 'v0' };
  }
  const d = gitIn(root, ['describe', '--tags', '--abbrev=0']);
  if (!d.ok || !d.out) return { root, hasGit: true, untagged: true, version: 'v0' };
  return { root, hasGit: true, untagged: false, version: d.out };
}

/**
 * The handbook's shared git directory — the one identity that survives worktrees. Every worktree
 * of a repo reports the SAME `--git-common-dir`, while their working-tree paths all differ.
 */
function gitCommonDir(root) {
  const r = gitIn(root, ['rev-parse', '--git-common-dir']);
  if (!r.ok || !r.out) return null;
  return realPath(require('path').resolve(root, r.out));
}

/**
 * Resolve symlinks before comparing paths, falling back to the input when the path does not exist.
 *
 * Not optional pedantry: git answers `--git-common-dir` RELATIVELY from a main checkout (`.git`)
 * but ABSOLUTELY, and already symlink-resolved, from a worktree. So the two sides of the comparison
 * arrive in different forms, and any handbook checkout reached through a symlinked path (`/tmp` on
 * macOS, a symlinked home, a network mount) produced two different strings for one directory —
 * making the repo fail to recognise itself.
 */
function realPath(p) {
  try { return require('fs').realpathSync(p); } catch (_) { return p; }
}

/**
 * Is `repoPath` the handbook itself? Both tools must answer this identically, so it is answered
 * ONCE, here — the same reason stamp reading lives here.
 *
 * NOT a path-string comparison, and that is the whole point. `colab update` used to test
 * `abs === handbookRoot`, which silently answers "no" whenever the CLI runs from a git WORKTREE of
 * the handbook: the CLI locates its root by walking up from its own file (giving the worktree),
 * while the fleet registry names the main checkout. Same repo, two spellings, and the handbook was
 * audited as its own consumer — reported `unstamped`, with advice to stamp its own CLAUDE.md as a
 * copy of a version of itself. Comparing git common dirs is immune to that: worktree, symlink or
 * a differently-spelled path all resolve to one identity.
 *
 * Remote (owner/name) targets are out of scope: recognising "self" through the API would need the
 * name match this deliberately avoids.
 */
function isHandbookItself(repoPath, handbookRoot) {
  const { resolve } = require('path');
  if (!repoPath || !handbookRoot) return false;
  const root = realPath(resolve(repoPath));
  if (root === realPath(resolve(handbookRoot))) return true;
  const a = gitCommonDir(root);
  const b = gitCommonDir(handbookRoot);
  return a !== null && b !== null && a === b;
}

/** Template stems present in the handbook (e.g. "ci-node", "ci-laravel", "release-tag"). */
function templateNames(root) {
  const { readdirSync } = require('fs');
  const { join } = require('path');
  try {
    return new Set(
      readdirSync(join(root, 'templates'))
        .filter((f) => /\.ya?ml$/.test(f))
        .map((f) => f.replace(/\.ya?ml$/, '')),
    );
  } catch (_) {
    return new Set();
  }
}

/** Both spellings a template file may use, as repo-relative paths for `git log`/`git show`. */
function templateFiles(name) {
  return [`templates/${name}.yml`, `templates/${name}.yaml`];
}

/**
 * Did any of the given template files change between the stamped version and HEAD?
 * Returns { verifiable, changed }. verifiable=false when the stamped ref does not resolve in this
 * checkout (a tag we do not have) — reported, never guessed.
 *
 * This is the check that keeps releases quiet: comparing version STRINGS would mark every adopter
 * stale on every handbook release, including releases that touched nothing they copied.
 */
function templateChangedSince(root, files, sinceRef) {
  const resolvable = gitIn(root, ['rev-parse', '--verify', '--quiet', sinceRef + '^{commit}']).ok;
  if (!resolvable) return { verifiable: false, changed: false };
  const log = gitIn(root, ['log', '--oneline', `${sinceRef}..HEAD`, '--', ...files]);
  return { verifiable: true, changed: log.ok && log.out.length > 0 };
}

/**
 * A template's content AS OF a given ref (`git show <ref>:templates/<name>.yml`), or null.
 * Divergence detection stands entirely on this: to know whether a copy was hand-edited you must
 * compare it against what it was copied FROM, not against what the template has since become.
 * Comparing against the current template would call every out-of-date copy "hand-edited".
 */
function templateAt(root, ref, name) {
  for (const f of templateFiles(name)) {
    const r = gitIn(root, ['show', `${ref}:${f}`]);
    if (r.ok) return r.out;
  }
  return null;
}

// ---------------------------------------------------------------------------
// stamps
// ---------------------------------------------------------------------------

/** The canonical workflow stamp line. `colab template` writes it; `colab update` rewrites it. */
function stampLine(name, version) {
  return `# colab-handbook: ${name} @ ${version}\n`;
}

/** Workflow stamp: `# colab-handbook: <name> @ <version>`. */
function parseWorkflowStamp(text) {
  if (!text) return null;
  const m = text.match(/#\s*colab-handbook:\s*([A-Za-z0-9._-]+)\s*@\s*(v?[0-9][0-9A-Za-z.\-+]*)/);
  return m ? { name: m[1], version: m[2] } : null;
}

/** CLAUDE-block stamp: `<!-- colab-handbook @ <version> -->`. */
function parseClaudeStamp(text) {
  if (!text) return null;
  const m = text.match(/<!--\s*colab-handbook\s*@\s*(v?[0-9][0-9A-Za-z.\-+]*)\s*-->/);
  return m ? { version: m[1] } : null;
}

/**
 * Content fingerprints that mark a workflow as a handbook derivative even when someone renamed the
 * file or dropped the stamp.
 *
 * THE ADMISSION TEST, and it is the whole design: *could this string appear in a file nobody copied
 * from us?* If yes, it is not a fingerprint — it is the STACK'S VOCABULARY, and matching on it
 * accuses every repo that happens to use that stack. We shipped two such strings and both misfired
 * on real repos:
 *
 *   - `wayfinder:generate` — a framework command, not our text. ANY workflow doing build-time
 *     codegen on that framework contains it, whatever its origin. It flagged three hand-written
 *     deploy workflows that had never been near a template.
 *   - `gitleaks/gitleaks/releases/download` — the upstream release URL. It identifies gitleaks,
 *     not us. Two hand-written CI files on this fleet contain it (including this handbook's own),
 *     copied from each other rather than from `templates/`.
 *
 * What survives is text WE COINED: the step names in our templates. No upstream tool, framework or
 * generator emits "Resolve toolchain versions"; a file containing it was typed by us or copied from
 * something that was. Each entry is therefore matched as a STEP NAME (`- name: <marker>`), not as a
 * loose substring — so prose that merely mentions the phrase (a comment, a README, this file) does
 * not trip it.
 *
 * `template` attributes the evidence, which is what lets the advice name a real template instead of
 * a `<name>` placeholder the reader has to guess. `null` means the marker is shared by several
 * templates: it still proves derivation, but not FROM WHICH — and the advice must then say so
 * rather than pick one.
 *
 * Precise on purpose: better to miss an unstamped copy than to nag a file we cannot attribute.
 */
const WORKFLOW_FINGERPRINTS = [
  // Header lines — verbatim template prose, and self-attributing.
  { marker: 'CI (Node) — TEMPLATE. Copy me into your repo', kind: 'text', template: 'ci-node' },
  { marker: 'CI (Laravel) — TEMPLATE. Copy me into your repo', kind: 'text', template: 'ci-laravel' },
  { marker: 'CI (Python) — TEMPLATE. Copy me into your repo', kind: 'text', template: 'ci-python' },
  { marker: 'Release (tag) — TEMPLATE. Copy me into your repo', kind: 'text', template: 'release-tag' },
  { marker: 'Deploy (SSH/rsync to shared hosting) — TEMPLATE. Copy me into your repo', kind: 'text', template: 'deploy-xserver' },
  // The header convention itself, unattributed: this catches a copy of any template ADDED LATER
  // without anyone remembering to extend this list — provided the new template keeps the house
  // header. A template that omits it is invisible here, which is worth knowing when writing one.
  { marker: '— TEMPLATE. Copy me into your repo', kind: 'text', template: null },
  // Step names we coined, one per template.
  { marker: 'Resolve Node version', kind: 'step', template: 'ci-node' },
  { marker: 'Detect optional scripts', kind: 'step', template: 'ci-node' },
  { marker: 'Resolve toolchain versions', kind: 'step', template: 'ci-laravel' },
  { marker: 'Prepare throwaway env for build-time codegen (wayfinder)', kind: 'step', template: 'ci-laravel' },
  { marker: 'Resolve Python version', kind: 'step', template: 'ci-python' },
  { marker: 'Detect optional tooling', kind: 'step', template: 'ci-python' },
  { marker: 'Build grouped release summary', kind: 'step', template: 'release-tag' },
  { marker: 'Resolve tag and previous tag', kind: 'step', template: 'release-tag' },
  // deploy-xserver. These two were CHOSEN to differ from the step names in the hand-written deploy
  // workflows this template was derived from ("Setup Node", "Smoke test (…)"), which is the same
  // admission test as above read from the other end: those files must keep classifying as
  // `unrelated`, and a marker they happen to contain would reclassify them as copies and invite an
  // overwrite. Verified against all three before being added here.
  { marker: 'Resolve deploy toolchain', kind: 'step', template: 'deploy-xserver' },
  { marker: 'Verify the deployed site answers', kind: 'step', template: 'deploy-xserver' },
  // Shared by all three ci-* templates: proves derivation, cannot say from which. Note the exact
  // parenthetical — hand-written installers on this fleet say "(pinned binary)", which is why the
  // step NAME discriminates where the URL inside the step does not.
  { marker: 'Install gitleaks (pinned release binary)', kind: 'step', template: null },
];

function reEscape(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Does one fingerprint match? Step markers must appear as an actual `- name:` step, not as prose. */
function fingerprintHits(text, fp) {
  if (fp.kind === 'text') return text.includes(fp.marker);
  return new RegExp(`^\\s*-\\s*name:\\s*["']?${reEscape(fp.marker)}["']?\\s*$`, 'm').test(text);
}

/**
 * Where did an UNSTAMPED workflow come from? Returns { origin, template, evidence }:
 *
 *   derived    content evidence says it is a handbook copy. `template` names it when the evidence
 *              attributes one, else null (derivation proven, source not).
 *   name-only  the FILENAME matches a template but the content carries none of it. This is the
 *              dangerous case, and it is why a name match is no longer sufficient on its own: the
 *              moment `templates/<x>.yml` is added for some `x` that repos already have as their
 *              own hand-written workflow, a name-only match would advise `--force` and OVERWRITE
 *              a file that never came from us. A shared name is a coincidence, not a lineage.
 *   none       neither. Somebody's own workflow — say nothing about it, ever.
 */
function workflowProvenance(text, stem, tmplNames) {
  const hits = text ? WORKFLOW_FINGERPRINTS.filter((fp) => fingerprintHits(text, fp)) : [];
  if (hits.length) {
    const named = [...new Set(hits.map((h) => h.template).filter(Boolean))];
    // One attributed template wins; several (or none) fall back to the filename, and only if that
    // is a real template name. Never guess.
    const template = named.length === 1 ? named[0] : (tmplNames.has(stem) ? stem : null);
    // Cite only the most specific form of each match: the generic header rule always fires
    // alongside the attributed one, and quoting both back at the reader reads like two findings.
    const markers = hits.map((h) => h.marker);
    const evidence = markers.filter((m) => !markers.some((o) => o !== m && o.includes(m)));
    return { origin: 'derived', template, evidence };
  }
  if (tmplNames.has(stem)) return { origin: 'name-only', template: stem, evidence: [] };
  return { origin: 'none', template: null, evidence: [] };
}

/**
 * The single source of the advice both tools print, so the two can never drift apart on the one
 * thing that matters here: whether to suggest asserting provenance.
 * Returns null when there is nothing honest to say.
 */
function unstampedFinding(prov) {
  if (prov.origin === 'derived') {
    const why = `matched handbook template text (${prov.evidence.map((e) => `"${e}"`).join(', ')})`;
    const how = prov.template
      ? `re-copy deliberately with \`colab template ${prov.template} --force\``
      : 'identify which template it came from before re-copying — the evidence proves it is a copy but not of which template';
    return {
      state: 'unstamped',
      reason: `${why} but carries no stamp — lineage unknown, so replacing it could destroy unknown edits; ${how}`,
    };
  }
  if (prov.origin === 'name-only') {
    return {
      state: 'unrelated',
      reason: `shares a name with templates/${prov.template} but contains none of that template's text — treated as this repo's own file. A matching NAME is not lineage: do NOT \`colab template ${prov.template} --force\`, it would overwrite work that never came from here.`,
    };
  }
  return null;
}

/** Boolean view, kept for callers that only ask "is this ours?". A shared NAME alone is not. */
function looksLikeHandbookWorkflow(text, stem, tmplNames) {
  return workflowProvenance(text, stem, tmplNames).origin === 'derived';
}

/** A CLAUDE.md that pasted the conventions block (this line is unique to the block template). */
function looksLikeHandbookClaude(text) {
  return !!text && /follows the \[?colab-handbook/i.test(text);
}

// ---------------------------------------------------------------------------
// version comparison
// ---------------------------------------------------------------------------

/** Element-wise numeric compare; missing components count as 0. */
function cmpParts(a, b) {
  const n = Math.max(a.length, b.length);
  for (let i = 0; i < n; i++) {
    const x = a[i] ?? 0;
    const y = b[i] ?? 0;
    if (x !== y) return x < y ? -1 : 1;
  }
  return 0;
}

/** vX.Y.Z comparison. Non-numeric junk sorts as 0 so a malformed stamp never throws. */
function cmpSemver(a, b) {
  const norm = (s) => String(s).replace(/^v/i, '').split('.').map((n) => parseInt(n, 10) || 0);
  return cmpParts(norm(a), norm(b));
}

// ---------------------------------------------------------------------------
// classification — the heart of `colab update`
// ---------------------------------------------------------------------------

// Compare tolerantly at the edges only: line endings and trailing blank lines are noise no adopter
// chose. Anything else counts as a real edit — under-reporting divergence here would let the tool
// overwrite someone's work, which is the one outcome it must never produce.
function sameContent(a, b) {
  const norm = (s) => String(s).replace(/\r\n/g, '\n').replace(/\s+$/, '');
  return norm(a) === norm(b);
}

/**
 * Classify one stamped artifact. Returns { state, reason, from, to }.
 *
 *   current    the stamp is the handbook's version, OR the template genuinely has not changed
 *              since that stamp. Nothing to do.
 *   behind     the stamp is older AND the template changed in between AND the local copy is
 *              still pristine as of its own stamp — so it can be regenerated safely.
 *   diverged   the local copy does not match the template AS OF ITS OWN STAMP: someone edited it.
 *              Copy-and-own makes that legitimate (§7), so it is reported and never written.
 *   unstamped  lineage unknown — handled by the caller, which can see it has no stamp at all.
 *   n-a        cannot be assessed, with a stated reason (unknown template, a stamp from a version
 *              not in this checkout, a stamp newer than the handbook). Never silent.
 *
 * `comparable: false` (the CLAUDE block) means the artifact's pristine form cannot be reconstructed,
 * so divergence is undecidable and the classification stops at current/behind.
 */
function classifyStamped(opts) {
  const { root, hb, templateName, stampVersion, localText, comparable = true, tmplNames } = opts;

  if (hb.untagged || !hb.hasGit) {
    return { state: 'n-a', reason: 'handbook is untagged — stamp comparison inactive', from: stampVersion, to: hb.version };
  }
  if (templateName !== null && !tmplNames.has(templateName)) {
    return { state: 'n-a', reason: `names unknown template "${templateName}" — not in the handbook's templates/`, from: stampVersion, to: hb.version };
  }
  if (cmpSemver(stampVersion, hb.version) > 0) {
    return { state: 'n-a', reason: `stamp is NEWER than handbook ${hb.version} — clock skew or a hand-edited stamp`, from: stampVersion, to: hb.version };
  }

  const files = templateName === null ? [CLAUDE_BLOCK_TEMPLATE] : templateFiles(templateName);
  const { verifiable, changed } = templateChangedSince(root, files, stampVersion);
  if (!verifiable) {
    return { state: 'n-a', reason: `stamped @ ${stampVersion}, a version not in this handbook checkout — fetch tags, or re-copy`, from: stampVersion, to: hb.version };
  }
  if (!changed) {
    const why = cmpSemver(stampVersion, hb.version) === 0
      ? 'stamped at the current handbook version'
      : `template unchanged since ${stampVersion}`;
    return { state: 'current', reason: why, from: stampVersion, to: hb.version };
  }

  // The template moved. Whether we may refresh depends on whether the copy is still pristine.
  if (!comparable) {
    return { state: 'behind', reason: 'template changed since this stamp', from: stampVersion, to: hb.version };
  }
  const pristine = templateAt(root, stampVersion, templateName);
  if (pristine === null) {
    return { state: 'n-a', reason: `cannot read templates/${templateName} at ${stampVersion} — cannot tell pristine from edited`, from: stampVersion, to: hb.version };
  }
  const expected = stampLine(templateName, stampVersion) + pristine;
  if (sameContent(localText, expected)) {
    return { state: 'behind', reason: 'pristine copy, template changed since this stamp', from: stampVersion, to: hb.version };
  }
  return { state: 'diverged', reason: `hand-edited since it was copied @ ${stampVersion} — copy-and-own, review by hand`, from: stampVersion, to: hb.version };
}

/**
 * Classify the frozen CLI copy: { state, reason, from, to }, with state one of
 * current / behind / n-a.
 *
 * Deliberately the SAME question as classifyStamped asks of a template copy — "did the thing you
 * copied actually change between your stamp and HEAD?", answered by `git log`, not by comparing
 * version strings — so a handbook release that touched no CLI code does not tell every machine its
 * frozen copy is stale. The version comparison and the git read are the ones above; nothing about
 * "behind" is decided twice.
 *
 * No `diverged` state, and that is the one real difference from a template copy. A template is
 * copy-and-own: the adopter is entitled to edit it, so an edit must be detected and protected. The
 * frozen CLI is a CACHE of this repo's own tool — nobody owns it, install.sh overwrites it wholesale
 * on every run, and a hand-edited one is a machine to fix, not an edit to preserve.
 */
function classifyFrozen(opts) {
  const { root, hb, stampVersion } = opts;

  if (hb.untagged || !hb.hasGit) {
    return { state: 'n-a', reason: 'handbook is untagged — stamp comparison inactive', from: stampVersion || null, to: hb.version };
  }
  if (!stampVersion) {
    return { state: 'n-a', reason: `no ${FROZEN_STAMP_FILE} beside the frozen copy — lineage unknown, re-run install.sh --tools`, from: null, to: hb.version };
  }
  if (cmpSemver(stampVersion, hb.version) > 0) {
    return { state: 'n-a', reason: `stamp is NEWER than handbook ${hb.version} — this machine froze from a checkout ahead of here`, from: stampVersion, to: hb.version };
  }

  const { verifiable, changed } = templateChangedSince(root, FROZEN_SOURCES, stampVersion);
  if (!verifiable) {
    return { state: 'n-a', reason: `stamped @ ${stampVersion}, a version not in this handbook checkout — fetch tags, or re-freeze`, from: stampVersion, to: hb.version };
  }
  if (!changed) {
    const why = cmpSemver(stampVersion, hb.version) === 0
      ? 'frozen at the current handbook version'
      : `CLI unchanged since ${stampVersion}`;
    return { state: 'current', reason: why, from: stampVersion, to: hb.version };
  }
  return { state: 'behind', reason: `the CLI changed since ${stampVersion} — re-run install.sh --tools to re-freeze`, from: stampVersion, to: hb.version };
}

module.exports = {
  CLAUDE_BLOCK_TEMPLATE, WORKFLOW_FINGERPRINTS,
  FROZEN_STAMP_NAME, FROZEN_STAMP_FILE, FROZEN_SOURCES, classifyFrozen,
  gitIn, gitCommonDir, isHandbookItself,
  handbookInfo, templateNames, templateFiles, templateChangedSince, templateAt,
  stampLine, parseWorkflowStamp, parseClaudeStamp,
  fingerprintHits, workflowProvenance, unstampedFinding,
  looksLikeHandbookWorkflow, looksLikeHandbookClaude,
  cmpParts, cmpSemver, sameContent, classifyStamped,
};
