'use strict';
/**
 * Stamp + drift logic, shared by `audit/audit.mjs` (report) and `colab update` (report + refresh).
 *
 * Copy-and-own means nothing is pushed to an adopter: a copied artifact carries a STAMP naming
 * the template and the handbook version it came from, and drift is discovered by comparing that
 * stamp against the handbook's own git history. Both tools must read stamps identically — a
 * second implementation that disagreed about what "behind" means is exactly the two-places-drift
 * disease this handbook exists to kill, so the reading lives here once.
 *
 * CommonJS on purpose: `tools/colab` is CJS, `audit/audit.mjs` is ESM. CJS is the format both can
 * consume (the audit pulls it in through `createRequire`); the reverse is not true from a
 * synchronous CLI.
 *
 * Every function takes the handbook root explicitly rather than resolving it — the two callers
 * locate the handbook differently (the audit honours COLAB_HANDBOOK; the CLI walks up from its
 * own file), and a module that guessed would be wrong for one of them.
 */

const { execFileSync } = require('child_process');

// The artifact kinds that carry a stamp. Workflow copies are WHOLE-FILE copies, so a pristine one
// can be regenerated byte-for-byte. The CLAUDE block is a fragment pasted into a larger file whose
// placeholders the adopter fills in — see CLAUDE_BLOCK below.
const CLAUDE_BLOCK_TEMPLATE = 'templates/repo-CLAUDE-block.md';

// ---------------------------------------------------------------------------
// git access to the handbook checkout
// ---------------------------------------------------------------------------

function gitIn(root, args) {
  try {
    return {
      ok: true,
      out: execFileSync('git', ['-C', root, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim(),
    };
  } catch (_) {
    return { ok: false, out: '' };
  }
}

/**
 * The handbook's own identity: { root, hasGit, untagged, version }.
 * Before the first tag exists the version is 'v0' and `untagged` is true, which DEACTIVATES stamp
 * comparison in both callers — there is no real version line to compare against, and inventing one
 * would mark every adopter stale against a version that never shipped.
 */
function handbookInfo(root) {
  if (!gitIn(root, ['rev-parse', '--show-toplevel']).ok) {
    return { root, hasGit: false, untagged: true, version: 'v0' };
  }
  const d = gitIn(root, ['describe', '--tags', '--abbrev=0']);
  if (!d.ok || !d.out) return { root, hasGit: true, untagged: true, version: 'v0' };
  return { root, hasGit: true, untagged: false, version: d.out };
}

/** Template stems present in the handbook (e.g. "ci-node", "ci-laravel", "release-tag"). */
function templateNames(root) {
  const { readdirSync } = require('fs');
  const { join } = require('path');
  try {
    return new Set(
      readdirSync(join(root, 'templates'))
        .filter((f) => /\.ya?ml$/.test(f))
        .map((f) => f.replace(/\.ya?ml$/, '')),
    );
  } catch (_) {
    return new Set();
  }
}

/** Both spellings a template file may use, as repo-relative paths for `git log`/`git show`. */
function templateFiles(name) {
  return [`templates/${name}.yml`, `templates/${name}.yaml`];
}

/**
 * Did any of the given template files change between the stamped version and HEAD?
 * Returns { verifiable, changed }. verifiable=false when the stamped ref does not resolve in this
 * checkout (a tag we do not have) — reported, never guessed.
 *
 * This is the check that keeps releases quiet: comparing version STRINGS would mark every adopter
 * stale on every handbook release, including releases that touched nothing they copied.
 */
function templateChangedSince(root, files, sinceRef) {
  const resolvable = gitIn(root, ['rev-parse', '--verify', '--quiet', sinceRef + '^{commit}']).ok;
  if (!resolvable) return { verifiable: false, changed: false };
  const log = gitIn(root, ['log', '--oneline', `${sinceRef}..HEAD`, '--', ...files]);
  return { verifiable: true, changed: log.ok && log.out.length > 0 };
}

/**
 * A template's content AS OF a given ref (`git show <ref>:templates/<name>.yml`), or null.
 * Divergence detection stands entirely on this: to know whether a copy was hand-edited you must
 * compare it against what it was copied FROM, not against what the template has since become.
 * Comparing against the current template would call every out-of-date copy "hand-edited".
 */
function templateAt(root, ref, name) {
  for (const f of templateFiles(name)) {
    const r = gitIn(root, ['show', `${ref}:${f}`]);
    if (r.ok) return r.out;
  }
  return null;
}

// ---------------------------------------------------------------------------
// stamps
// ---------------------------------------------------------------------------

/** The canonical workflow stamp line. `colab template` writes it; `colab update` rewrites it. */
function stampLine(name, version) {
  return `# colab-handbook: ${name} @ ${version}\n`;
}

/** Workflow stamp: `# colab-handbook: <name> @ <version>`. */
function parseWorkflowStamp(text) {
  if (!text) return null;
  const m = text.match(/#\s*colab-handbook:\s*([A-Za-z0-9._-]+)\s*@\s*(v?[0-9][0-9A-Za-z.\-+]*)/);
  return m ? { name: m[1], version: m[2] } : null;
}

/** CLAUDE-block stamp: `<!-- colab-handbook @ <version> -->`. */
function parseClaudeStamp(text) {
  if (!text) return null;
  const m = text.match(/<!--\s*colab-handbook\s*@\s*(v?[0-9][0-9A-Za-z.\-+]*)\s*-->/);
  return m ? { version: m[1] } : null;
}

/**
 * Content fingerprints that mark a workflow/CLAUDE file as a handbook derivative even when someone
 * renamed the file or pasted the block without the stamp. Precise on purpose: better to miss an
 * unstamped copy than to nag an unrelated ci.yml.
 */
const WORKFLOW_FINGERPRINTS = [
  'gitleaks/gitleaks/releases/download', // our exact pinned-binary install
  'wayfinder:generate',                  // ci-laravel bootstrap
  'Build grouped release summary',       // release-tag
  'Resolve Node version',                // ci-node toolchain step
  'Resolve toolchain versions',          // ci-laravel toolchain step
];

function looksLikeHandbookWorkflow(text, stem, tmplNames) {
  if (tmplNames.has(stem)) return true;
  if (!text) return false;
  return WORKFLOW_FINGERPRINTS.some((s) => text.includes(s));
}

/** A CLAUDE.md that pasted the conventions block (this line is unique to the block template). */
function looksLikeHandbookClaude(text) {
  return !!text && /follows the \[?colab-handbook/i.test(text);
}

// ---------------------------------------------------------------------------
// version comparison
// ---------------------------------------------------------------------------

/** Element-wise numeric compare; missing components count as 0. */
function cmpParts(a, b) {
  const n = Math.max(a.length, b.length);
  for (let i = 0; i < n; i++) {
    const x = a[i] ?? 0;
    const y = b[i] ?? 0;
    if (x !== y) return x < y ? -1 : 1;
  }
  return 0;
}

/** vX.Y.Z comparison. Non-numeric junk sorts as 0 so a malformed stamp never throws. */
function cmpSemver(a, b) {
  const norm = (s) => String(s).replace(/^v/i, '').split('.').map((n) => parseInt(n, 10) || 0);
  return cmpParts(norm(a), norm(b));
}

// ---------------------------------------------------------------------------
// classification — the heart of `colab update`
// ---------------------------------------------------------------------------

// Compare tolerantly at the edges only: line endings and trailing blank lines are noise no adopter
// chose. Anything else counts as a real edit — under-reporting divergence here would let the tool
// overwrite someone's work, which is the one outcome it must never produce.
function sameContent(a, b) {
  const norm = (s) => String(s).replace(/\r\n/g, '\n').replace(/\s+$/, '');
  return norm(a) === norm(b);
}

/**
 * Classify one stamped artifact. Returns { state, reason, from, to }.
 *
 *   current    the stamp is the handbook's version, OR the template genuinely has not changed
 *              since that stamp. Nothing to do.
 *   behind     the stamp is older AND the template changed in between AND the local copy is
 *              still pristine as of its own stamp — so it can be regenerated safely.
 *   diverged   the local copy does not match the template AS OF ITS OWN STAMP: someone edited it.
 *              Copy-and-own makes that legitimate (§7), so it is reported and never written.
 *   unstamped  lineage unknown — handled by the caller, which can see it has no stamp at all.
 *   n-a        cannot be assessed, with a stated reason (unknown template, a stamp from a version
 *              not in this checkout, a stamp newer than the handbook). Never silent.
 *
 * `comparable: false` (the CLAUDE block) means the artifact's pristine form cannot be reconstructed,
 * so divergence is undecidable and the classification stops at current/behind.
 */
function classifyStamped(opts) {
  const { root, hb, templateName, stampVersion, localText, comparable = true, tmplNames } = opts;

  if (hb.untagged || !hb.hasGit) {
    return { state: 'n-a', reason: 'handbook is untagged — stamp comparison inactive', from: stampVersion, to: hb.version };
  }
  if (templateName !== null && !tmplNames.has(templateName)) {
    return { state: 'n-a', reason: `names unknown template "${templateName}" — not in the handbook's templates/`, from: stampVersion, to: hb.version };
  }
  if (cmpSemver(stampVersion, hb.version) > 0) {
    return { state: 'n-a', reason: `stamp is NEWER than handbook ${hb.version} — clock skew or a hand-edited stamp`, from: stampVersion, to: hb.version };
  }

  const files = templateName === null ? [CLAUDE_BLOCK_TEMPLATE] : templateFiles(templateName);
  const { verifiable, changed } = templateChangedSince(root, files, stampVersion);
  if (!verifiable) {
    return { state: 'n-a', reason: `stamped @ ${stampVersion}, a version not in this handbook checkout — fetch tags, or re-copy`, from: stampVersion, to: hb.version };
  }
  if (!changed) {
    const why = cmpSemver(stampVersion, hb.version) === 0
      ? 'stamped at the current handbook version'
      : `template unchanged since ${stampVersion}`;
    return { state: 'current', reason: why, from: stampVersion, to: hb.version };
  }

  // The template moved. Whether we may refresh depends on whether the copy is still pristine.
  if (!comparable) {
    return { state: 'behind', reason: 'template changed since this stamp', from: stampVersion, to: hb.version };
  }
  const pristine = templateAt(root, stampVersion, templateName);
  if (pristine === null) {
    return { state: 'n-a', reason: `cannot read templates/${templateName} at ${stampVersion} — cannot tell pristine from edited`, from: stampVersion, to: hb.version };
  }
  const expected = stampLine(templateName, stampVersion) + pristine;
  if (sameContent(localText, expected)) {
    return { state: 'behind', reason: 'pristine copy, template changed since this stamp', from: stampVersion, to: hb.version };
  }
  return { state: 'diverged', reason: `hand-edited since it was copied @ ${stampVersion} — copy-and-own, review by hand`, from: stampVersion, to: hb.version };
}

module.exports = {
  CLAUDE_BLOCK_TEMPLATE, WORKFLOW_FINGERPRINTS,
  gitIn, handbookInfo, templateNames, templateFiles, templateChangedSince, templateAt,
  stampLine, parseWorkflowStamp, parseClaudeStamp,
  looksLikeHandbookWorkflow, looksLikeHandbookClaude,
  cmpParts, cmpSemver, sameContent, classifyStamped,
};
